:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
:queues:
  # Queue names and their priorities (lower number means higher priority)
  - [critical, 1]
  - [default, 3]
  - [ai_images, 4]
  - [audio, 2]
